### PR TITLE
Update nntp_proxy.py

### PR DESCRIPTION
**Pull request by extremeshok**
Code cleanup and correct formatting
Remove deprecated has
PEP8 conformity (ignoring long lines #E501)

### CODE REVIEW

**Comment by ovpn-to** [comment]
dont push anything here. thank you.

**Comment by ovpn-to** [comment]
don't know why it looks like it looks, looks different in my editor. 
keep it in your fork, we won't update anything here and we use another private version.

**Comment by extremeshok** [comment]
No problem, I have heavily modified the v3 and am in the process of porting the extended features to the new code.

Most of the commits are in our private repo.

I figured It would be easier to pool resources than develop forks.

**Comment by ovpn-to** [comment]
yeah normally good idea but we won't maintain this code any more, published only for the ppl.

**Comment by ovpn-to** [comment]
added to honor your work!

**Pull request merged**
